site_name: Makuro Studio
# site_url: https://makurostudio.my.id
repo_url: https://github.com/malikkurosaki/makurostudio
repo_name: malikkurosaki/makurostudio
edit_uri: "/malikkurosaki/makurostudio/edit/main/docs/"
site_description: "ini adalah keterangannya"
site_author: "malikkurosaki"
remote_branch: "main"
# dev_addr: "localhost:8080"
nav:
  - "index.md"
  - "Tentang": about.md
  - "Flutter":
      - "Flutter": "flutter/flutter.md"
  - "JavaScript":
      - "vanila": "javascript/vanila.md"
      - "nodejs": "javascript/nodejs.md"
  - "package":
      - "nodejs":
          - "brainjs": "package/nodejs/brainjs.md"
  - "about me": "about_me.md"
theme:
  name: material
  logo: favicon.ico
  favicon: favicon.ico
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black

  features:
    - header.autohide
    - navigation.tabs
    - toc.follow
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
docs_dir: docs
copyright: Copyright &copy; 2022 Malikkurosaki
extra:
  consent:
    actions:
      - accept
      - manage
